kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /home/runner/work/adaptdl/adaptdl
    containerPath: /source
- role: worker
  extraMounts:
  - hostPath: /home/runner/work/adaptdl/adaptdl
    containerPath: /source
- role: worker
  extraMounts:
  - hostPath: /home/runner/work/adaptdl/adaptdl
    containerPath: /source
