apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adaptdl-pvc-local
  namespace: default
spec:
  storageClassName: local-storage
  volumeName: adaptdl-pvc-local
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adaptdl-pvc-local
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: adaptdl-pvc-local
    namespace: default
  capacity: 
    storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
