apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: adaptdl-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=adaptdl-sched'
    appkind: 'deployment'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: litmus-sa
  monitoring: false
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: adaptdl-experiment
      spec:
        components:
          env:
            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'
