name: "Controller tests"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: "./.github/kind/cluster.yaml"
          wait: "300s"
      - name: Block for cluster deployment
        run: |
          kubectl cluster-info
          kubectl wait node --all --timeout=300s --for condition=ready
          kubectl get nodes
          echo "All nodes ready"
          kubectl wait pod --all --all-namespaces --timeout=300s --for condition=ready
          echo "All pods ready"
      - name: Deploy AdaptDL
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install -r cli/requirements.txt
          helm repo add stable https://charts.helm.sh/stable
          make deploy
          kubectl get pods --all-namespaces | grep "adaptdl"
      - name: Deploy LitmusChaos
        run: |
          helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
          kubectl create ns litmus
          helm install chaos litmuschaos/litmus --namespace=litmus
          kubectl get pods -n litmus
          kubectl get crds | grep chaos
          kubectl annotate deploy/adaptdl-adaptdl-sched litmuschaos.io/chaos="true"
          kubectl create -f .github/litmuschaos/rbac.yaml
      - name: Run Tests
        run: |
          kubectl create -f .github/litmuschaos/delete.yaml
          sleep 60
          kubectl get all -n default
          kubectl get all -n litmus
          kubectl get pods
          kubectl wait pod adaptdl-runner --timeout=200s --for condition=ready
          kubectl wait pod adaptdl-runner --timeout=200s --for delete
          [[ $(kubectl get chaosresults -o jsonpath='{.items[*].status.experimentstatus.verdict}') == Pass ]] || kubectl get events --sort-by=.metadata.creationTimestamp | grep chaosresult
