name: "Controller tests"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: "./.github/kind/cluster.yaml"
          wait: "300s"
      - name: Deploy AdaptDL
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install -r cli/requirements.txt
          helm repo add stable https://charts.helm.sh/stable
          make deploy
          kubectl create -f .github/kind/local-storageclass.yaml
          kubectl create -f .github/kind/pvc.yaml
          kubectl get pods --all-namespaces | grep "adaptdl"
      - name: Create and Host Test Images
        run: |
          #docker build -f examples/linear_regression/Dockerfile . -t localhost:59283/adaptdl-example:latest
          #python3 cli/adaptdl_cli/proxy.py -p 59283 default \
          #     adaptdl-registry:registry docker push localhost:59283/adaptdl-example:latest
          docker build -f .github/litmuschaos/Dockerfile . -t localhost:59283/controller:latest
          python3 cli/adaptdl_cli/proxy.py -p 59283 default \
              adaptdl-registry:registry docker push localhost:59283/controller:latest
      - name: Deploy LitmusChaos
        run: |
          helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
          kubectl create ns litmus
          helm install chaos litmuschaos/litmus --namespace=litmus
          kubectl get pods -n litmus
          kubectl get crds | grep chaos
          kubectl annotate deploy/adaptdl-adaptdl-sched litmuschaos.io/chaos="true"
          kubectl create -f .github/litmuschaos/rbac.yaml
          kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.11.1?file=charts/generic/experiments.yaml
      - name: Block for cluster deployment
        run: |
          kubectl wait node --all --timeout=300s --for condition=ready
          kubectl get nodes
          echo "All nodes ready"
          kubectl wait pod --all --all-namespaces --timeout=300s --for condition=ready
          echo "All pods ready"
          kubectl get pods --all-namespaces | grep "adaptdl"
      - name: Run Tests
        run: |
          # Expand tests by adding new experiments and/or engines
          kubectl create -f .github/litmuschaos/adaptdlexperiment.yaml
          kubectl create -f .github/litmuschaos/engine.yaml
          sleep 10
          kubectl wait pod -l name=adaptdl-experiment --timeout=400s --for=condition=ready
          kubectl wait pod -l name=adaptdl-experiment --timeout=1200s --for=condition=delete

          kubectl get pods -l name=adaptdl-experiment
          kubectl describe chaosresults.litmuschaos.io
          kubectl get chaosresults.litmuschaos.io -o jsonpath='{.items[*].status.experimentstatus.verdict}' || kubectl get pods
          [[ $(kubectl get chaosresults.litmuschaos.io -o jsonpath='{.items[*].status.experimentstatus.verdict}') == Pass ]]
