name: "Controller tests"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: "./.github/kind/cluster.yaml"
          wait: "300s"
      - name: Block for cluster deployment
        run: |
          kubectl cluster-info
          kubectl wait node --all --timeout=300s --for condition=ready
          kubectl get nodes
          echo "All nodes ready"
          kubectl wait pod --all --all-namespaces --timeout=300s --for condition=ready
          echo "All pods ready"
      - name: Deploy AdaptDL
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install -r cli/requirements.txt
          helm repo add stable https://charts.helm.sh/stable
          make deploy
          kubectl get pods --all-namespaces | grep "adaptdl"
