name: "Controller tests"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: "./.github/kind/cluster.yaml"
          wait: "300s"
      - name: Block for cluster deployment
        run: |
          kubectl cluster-info
          kubectl wait node --all --timeout=300s --for condition=ready
          kubectl get nodes
          kubectl wait pod --all --all-namespaces --timeout=300s --for condition=ready
          echo "All nodes ready"
      - name: Deploy AdaptDL
        run: |
          make deploy
