name: "Controller tests"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: "./.github/kind/cluster.yaml"
          wait: "300s"
      - name: Block for cluster deployment
        run: |
          kubectl cluster-info
          kubectl wait node --all --timeout=300s --for condition=ready
          kubectl get nodes
          echo "All nodes ready"
          kubectl wait pod --all --all-namespaces --timeout=300s --for condition=ready
          echo "All pods ready"
      - name: Deploy AdaptDL
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install -r cli/requirements.txt
          helm repo add stable https://charts.helm.sh/stable
          make deploy
          kubectl create -f .github/kind/local-storageclass.yaml
          kubectl create -f .github/kind/pvc.yaml
          kubectl get pods --all-namespaces | grep "adaptdl"
          docker build -f examples/Dockerfile . -t localhost:59283/adaptdl-example:latest
          python3 cli/adaptdl_cli/proxy.py -p 59283 default \
              adaptdl-registry:registry docker push localhost:59283/adaptdl-example:latest
      - name: Deploy LitmusChaos
        run: |
          helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
          kubectl create ns litmus
          helm install chaos litmuschaos/litmus --namespace=litmus
          kubectl get pods -n litmus
          kubectl get crds | grep chaos
          kubectl annotate deploy/adaptdl-adaptdl-sched litmuschaos.io/chaos="true"
          kubectl create -f .github/litmuschaos/rbac.yaml
      - name: Run Tests
        run: |
          pwd
          kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.11.1?file=charts/generic/experiments.yaml
          for i in {0..9}; do kubectl create -f .github/litmuschaos/adaptdljob.yaml; done
          kubectl create -f .github/litmuschaos/delete.yaml
          sleep 10
          kubectl get all -n default
          kubectl get all -n litmus
          kubectl get pods
          kubectl wait pod adaptdl-runner --timeout=400s --for condition=ready
          kubectl wait pod adaptdl-runner --timeout=200s --for delete
          kubectl get chaosresults -o jsonpath='{.items[*].status.experimentstatus.verdict}'
          [[ $(kubectl get chaosresults -o jsonpath='{.items[*].status.experimentstatus.verdict}') == Pass ]]
          kubectl get adaptdljobs
          kubectl logs $(kubectl get pods -o name | grep linear | head -n 1)
